[versions]
adaptive = "1.1.0"
agp = "8.8.0"
appcompatV7 = "28.0.0"
foundation = "1.7.8"
gson = "2.11.0"
hiltAndroid = "2.51.1"
hiltNavigationCompose = "1.2.0"
inkAuthoring = "1.0.0-alpha03"
kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxSerializationJson = "1.8.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.03.00"
lifecycleViewmodelCompose = "2.8.7"
adaptiveNavigationAndroid = "1.1.0"
navigationRuntimeKtx = "2.8.9"
navigationCompose = "2.8.9"
roomKtx = "2.6.1"
roomRuntime = "2.6.1"
windowCore = "1.3.0"
ksp = "2.1.10-1.0.29"
roomCompiler = "2.6.1"
material3AdaptiveNavigationSuiteAndroidVersion = "1.3.1"
inkAuthoringAndroid = "1.0.0-alpha03"
inputMotionprediction = "1.0.0-beta05"

[libraries]
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-ink-authoring = { module = "androidx.ink:ink-authoring", version.ref = "inkAuthoring" }
androidx-ink-brush = { module = "androidx.ink:ink-brush", version.ref = "inkAuthoring" }
androidx-ink-geometry = { module = "androidx.ink:ink-geometry", version.ref = "inkAuthoring" }
androidx-ink-nativeloader = { module = "androidx.ink:ink-nativeloader", version.ref = "inkAuthoring" }
androidx-ink-rendering = { module = "androidx.ink:ink-rendering", version.ref = "inkAuthoring" }
androidx-ink-strokes = { module = "androidx.ink:ink-strokes", version.ref = "inkAuthoring" }
androidx-ink-storage = { module = "androidx.ink:ink-storage", version.ref = "inkAuthoring" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
appcompat-v7 = { module = "com.android.support:appcompat-v7", version.ref = "appcompatV7" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-adaptive-navigation-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation-android", version.ref = "adaptiveNavigationAndroid" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "windowCore" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material3-adaptive-navigation-suite-android = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite-android", version.ref = "material3AdaptiveNavigationSuiteAndroidVersion" }
androidx-ink-authoring-android = { group = "androidx.ink", name = "ink-authoring-android", version.ref = "inkAuthoringAndroid" }
androidx-input-motionprediction = { group = "androidx.input", name = "input-motionprediction", version.ref = "inputMotionprediction" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }